apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../../../../apps/training-operator/upstream/overlays/kubeflow

patchesStrategicMerge:
- ./configs/addfinalizer-edit.yaml
- ./configs/addfinalizer-view.yaml
- ./configs/addfinalizer-training.yaml

